CREATE DATABASE IF NOT EXISTS dr_robe_auth;

CREATE DATABASE IF NOT EXISTS dr_robe_trading;
CREATE DATABASE IF NOT EXISTS dr_robe_shop;
CREATE DATABASE IF NOT EXISTS dr_robe_hotel;
CREATE DATABASE IF NOT EXISTS dr_robe_spa;
CREATE DATABASE IF NOT EXISTS dr_robe_staff;
CREATE DATABASE IF NOT EXISTS dr_robe_payment;

